[package]
name = "chelaid"
version = "0.0.0"
edition = "2021"
rust-version = "1.83.0"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
color-eyre = "0.6.3"
env_logger = "0.11.6"
thiserror = "2.0.9"
